server:
  port: 9114
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
spring:
  application:
    name: bookusermgmt
  datasource:
    url: jdbc:mysql://localhost:3306/bookcase
    username: bookcase
    password: bookcase
    driver-class-name: com.mysql.jdbc.Driver